package com.sy.model.core.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Component;

import com.sy.common.MyBatisRepository;
import com.sy.model.core.domain.CmsNewsCategory;
import com.sy.model.core.domain.CmsNewsCategoryExample;

@MyBatisRepository
public interface CmsNewsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    int countByExample(CmsNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    int deleteByExample(CmsNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer nid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    int insert(CmsNewsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    int insertSelective(CmsNewsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    List<CmsNewsCategory> selectByExampleWithRowbounds(CmsNewsCategoryExample example, RowBounds rowBounds);

    
    
    List<CmsNewsCategory> selectByExampleByPage(CmsNewsCategoryExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    List<CmsNewsCategory> selectByExample(CmsNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    CmsNewsCategory selectByPrimaryKey(Integer nid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CmsNewsCategory record, @Param("example") CmsNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CmsNewsCategory record, @Param("example") CmsNewsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmsNewsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmsNewsCategory record);
}