package com.sy.model.core.domain;

import java.io.Serializable;
import java.util.Date;

public class CmsNewsCategory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news_category.nid
     *
     * @mbggenerated
     */
    private Integer nid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news_category.news_name
     *
     * @mbggenerated
     */
    private String newsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news_category.news_remark
     *
     * @mbggenerated
     */
    private String newsRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news_category.news_status
     *
     * @mbggenerated
     */
    private Byte newsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news_category.create_name
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news_category.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news_category.update_name
     *
     * @mbggenerated
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_news_category.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_news_category
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news_category.nid
     *
     * @return the value of cms_news_category.nid
     *
     * @mbggenerated
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news_category.nid
     *
     * @param nid the value for cms_news_category.nid
     *
     * @mbggenerated
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news_category.news_name
     *
     * @return the value of cms_news_category.news_name
     *
     * @mbggenerated
     */
    public String getNewsName() {
        return newsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news_category.news_name
     *
     * @param newsName the value for cms_news_category.news_name
     *
     * @mbggenerated
     */
    public void setNewsName(String newsName) {
        this.newsName = newsName == null ? null : newsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news_category.news_remark
     *
     * @return the value of cms_news_category.news_remark
     *
     * @mbggenerated
     */
    public String getNewsRemark() {
        return newsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news_category.news_remark
     *
     * @param newsRemark the value for cms_news_category.news_remark
     *
     * @mbggenerated
     */
    public void setNewsRemark(String newsRemark) {
        this.newsRemark = newsRemark == null ? null : newsRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news_category.news_status
     *
     * @return the value of cms_news_category.news_status
     *
     * @mbggenerated
     */
    public Byte getNewsStatus() {
        return newsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news_category.news_status
     *
     * @param newsStatus the value for cms_news_category.news_status
     *
     * @mbggenerated
     */
    public void setNewsStatus(Byte newsStatus) {
        this.newsStatus = newsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news_category.create_name
     *
     * @return the value of cms_news_category.create_name
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news_category.create_name
     *
     * @param createName the value for cms_news_category.create_name
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news_category.create_time
     *
     * @return the value of cms_news_category.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news_category.create_time
     *
     * @param createTime the value for cms_news_category.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news_category.update_name
     *
     * @return the value of cms_news_category.update_name
     *
     * @mbggenerated
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news_category.update_name
     *
     * @param updateName the value for cms_news_category.update_name
     *
     * @mbggenerated
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_news_category.update_time
     *
     * @return the value of cms_news_category.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_news_category.update_time
     *
     * @param updateTime the value for cms_news_category.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}